# Generated by Django 2.2.6 on 2019-10-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0004_auto_20191007_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsource',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_doc.Review'),
        ),
        migrations.RemoveField(
            model_name='reportsource',
            name='expertise',
        ),
        migrations.AddField(
            model_name='reportsource',
            name='expertise',
            field=models.ManyToManyField(to='rate_doc.Expertise'),
        ),
    ]
