# Generated by Django 2.2.6 on 2019-10-08 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0005_auto_20191007_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rate_doc.Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_doc.Review'),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='source',
            field=models.ForeignKey(help_text='Please use the following format: name (year born)', on_delete=django.db.models.deletion.CASCADE, to='rate_doc.Source'),
        ),
    ]
