# Generated by Django 2.2.5 on 2019-09-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='media_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_doc.MediaOrg'),
        ),
        migrations.AlterField(
            model_name='report',
            name='page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='section',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
