# Generated by Django 2.2.5 on 2019-09-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0002_auto_20190930_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='assignedTo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='rated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
