# Generated by Django 2.2.6 on 2019-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0006_auto_20191008_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='span_class',
            field=models.CharField(default='.no-span', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsource',
            name='span_class',
            field=models.CharField(default='.no-span', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsourceaffiliation',
            name='span_class',
            field=models.CharField(default='.no-span', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_html',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
