# Generated by Django 2.2.7 on 2019-11-21 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_doc', '0009_action_reportaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Report'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Review'),
        ),
        migrations.AlterField(
            model_name='mediaorg',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.MediaType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='media_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rate_doc.MediaOrg'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Action'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Report'),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Review'),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.ReportSourceAffiliation'),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Report'),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Review'),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='source',
            field=models.ForeignKey(help_text='Please use the following format: name (year born)', on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Source'),
        ),
        migrations.AlterField(
            model_name='reportsourceaffiliation',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Affiliation'),
        ),
        migrations.AlterField(
            model_name='reportsourceaffiliation',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Expertise'),
        ),
        migrations.AlterField(
            model_name='reportsourceaffiliation',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rate_doc.Report'),
        ),
    ]
